version: 2

updates:
  - package-ecosystem: "terraform"
    directories:
      - "/"
      - "/workspace"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
